apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: mdq-distilbert-commodity
  namespace: default
  labels:
    app.kubernetes.io/name: mdq-distilbert
    scenarios.ai.sap.com/id: mdq-commodity-classification
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    artifacts: []
    parameters: []
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      annotations:
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "1"
    spec:
      predictor:
        imagePullSecrets:
          - name: docker-secret
        containers:
          - name: kserve-container
            image: ektasoni/mdq-distilbert:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: MODEL_DIR
                value: /app/model
              - name: PORT
                value: "8080"
            resources:
              requests:
                cpu: "1"
                memory: "2Gi"
              limits:
                cpu: "2"
                memory: "4Gi"
